modLoader = "javafml"
loaderVersion = "[37,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/Seniorendi/AdvancedPeripherals/issues"
logoFile = "pack.png"
[[mods]]
modId = "advancedperipherals"
version = "${file.jarVersion}"
displayName = "Advanced Peripherals"
displayURL = "https://docs.srendi.de/"
authors = "Srendi"
description = '''
Advanced Peripherals is a mod that adds many useful extensions for CC:Tweaked(Computercraft).
You can communicate with Rerfined Storage, Applied Energistics 2 or with the whole Minecraft world.
Adds things like the Me Bridge, various types of turtles, the Chat Box and more.
'''
[[dependencies.advancedperipherals]]
modId = "forge"
mandatory = true
versionRange = "[39.0.55,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "computercraft"
mandatory = true
versionRange = "[1.99.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "curios"
mandatory = false
versionRange = "[1.18-5.0.2.3,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "ae2"
mandatory = false
versionRange = "[10.0.0-beta.1,)"
ordering = "NONE"
side = "BOTH"