modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/Seniorendi/AdvancedPeripherals/issues"
logoFile = "pack.png"
[[mods]]
modId = "advancedperipherals"
version = "0.4.2b"
displayName = "Advanced Peripherals"
#updateJSONURL="http://myurl.me/"
displayURL = "https://srendi.de/"
#logoFile="examplemod.png"
authors = "Sr_endi"
description = '''
A Peripheral addon mod for Computercraft. Adds things like the Me Bridge, the Chat Box and more.
'''
[[dependencies.advancedperipherals]]
modId = "forge"
mandatory = true
versionRange = "[36.0.21,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "minecraft"
mandatory = true
versionRange = "1.16.5"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "computercraft"
mandatory = true
versionRange = "1.95.2"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "appliedenergistics2"
mandatory = false
versionRange = "8.2.0"
ordnering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "refinedstorage"
mandatory = false
versionRange = "[1.9.12,)"
ordnering = "NONE"
side = "BOTH"