modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="advancedperipherals"
version="0.1"
displayName="Advanced Peripherals"
#updateJSONURL="http://myurl.me/"
displayURL="https://srendi.de/"
#logoFile="examplemod.png"
authors="Sr_endi"
description='''
Advanced Peripherals adds' a lot of new features for Computercraft.
'''
[[dependencies.advancedperipherals]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.advancedperipherals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.16.4]"
    ordering="NONE"
    side="BOTH"
